### ISSUE TITLE
How do I determine if the extracted content is iocs and not legitimate software information

### ISSUE THREAD

**Issue by LionelDong** [malicialab/iocsearcher#2]
if info@test.org in PDF is harmless, how to check

**Comment by malicialab** [comment]
Similar to other indicator extraction tools, filtering of benign indicators (i.e., those that are not IOCs) is a separate step not addressed by iocsearcher since it is highly application-specific. I will update the README to clarify this.

**Comment by malicialab** [comment]
I have updated the README with a Filtering paragraph, hope that helps. Closing this issue
