### ISSUE TITLE
Issues with configparser with python 3.12.x

### ISSUE THREAD

**Issue by MidavSec** [malicialab/iocsearcher#5]
Hi,

first thanks for iocsearch, love it to use. I upgraded my python to latest version and experience this issue:

   searcher = Searcher()
               ^^^^^^^^^^
  File "/opt/gms/venv/lib/python3.12/site-packages/iocsearcher/searcher.py", line 96, in __init__
    num_patterns = self.read_patterns(self.patterns_ini)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/gms/venv/lib/python3.12/site-packages/iocsearcher/searcher.py", line 792, in read_patterns
    config = ConfigParser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?

┌──(venv)─(root㉿kali)-[/opt/gms/prod/bc]
└─# python --version

Python 3.12.6

would be great to receive an advice how to fix it. Thanks

**Comment by malicialab** [comment]
Hi,
There was some legacy configparser code that has been removed in Python 3.12
I have replaced that code and submitted a new package version 2.4.2 that should fix it
Please upgrade and close this issue if the update works for you

**Comment by MidavSec** [comment]
Works, much appreciated!
